<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PayrollComponentSeeder extends Seeder
{
    public function run(): void
    {
        $components = [
            [
                'code' => 'BASIC',
                'name' => 'Basic Salary',
                'category' => 'earning',
                'component_type' => 'basic',
                'calculation_method' => 'fixed',
                'taxable' => true,
                'pro_ratable' => true,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => true,
                'display_order' => 10,
            ],
            [
                'code' => 'DA',
                'name' => 'Dearness Allowance',
                'category' => 'earning',
                'component_type' => 'allowance',
                'calculation_method' => 'fixed',
                'taxable' => true,
                'pro_ratable' => true,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => true,
                'display_order' => 20,
            ],
            [
                'code' => 'HRA',
                'name' => 'House Rent Allowance',
                'category' => 'earning',
                'component_type' => 'allowance',
                'calculation_method' => 'percentage_of_component',
                'taxable' => true,
                'pro_ratable' => true,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => true,
                'display_order' => 30,
            ],
            [
                'code' => 'CONVEYANCE',
                'name' => 'Conveyance Allowance',
                'category' => 'earning',
                'component_type' => 'allowance',
                'calculation_method' => 'fixed',
                'taxable' => true,
                'pro_ratable' => true,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => true,
                'display_order' => 40,
            ],
            [
                'code' => 'MEDICAL',
                'name' => 'Medical Allowance',
                'category' => 'earning',
                'component_type' => 'allowance',
                'calculation_method' => 'fixed',
                'taxable' => true,
                'pro_ratable' => true,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => true,
                'display_order' => 50,
            ],
            [
                'code' => 'OTHER_ALLOWANCE',
                'name' => 'Other Allowance',
                'category' => 'earning',
                'component_type' => 'allowance',
                'calculation_method' => 'fixed',
                'taxable' => true,
                'pro_ratable' => true,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => true,
                'display_order' => 60,
            ],
            [
                'code' => 'OT_PAY',
                'name' => 'Overtime Pay',
                'category' => 'earning',
                'component_type' => 'other',
                'calculation_method' => 'per_hour',
                'taxable' => true,
                'pro_ratable' => false,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 70,
            ],
            [
                'code' => 'BONUS',
                'name' => 'Bonus',
                'category' => 'earning',
                'component_type' => 'bonus',
                'calculation_method' => 'manual_input',
                'taxable' => true,
                'pro_ratable' => false,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 80,
            ],
            [
                'code' => 'ARREARS',
                'name' => 'Salary Arrears',
                'category' => 'earning',
                'component_type' => 'adjustment',
                'calculation_method' => 'manual_input',
                'taxable' => true,
                'pro_ratable' => false,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 90,
            ],
            [
                'code' => 'PF_EMPLOYEE',
                'name' => 'Provident Fund Employee',
                'category' => 'deduction',
                'component_type' => 'statutory',
                'calculation_method' => 'percentage_of_component',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 200,
            ],
            [
                'code' => 'PF_EMPLOYER',
                'name' => 'Provident Fund Employer',
                'category' => 'employer_contribution',
                'component_type' => 'statutory',
                'calculation_method' => 'percentage_of_component',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => false,
                'employer_only' => true,
                'arrear_eligible' => false,
                'display_order' => 210,
            ],
            [
                'code' => 'ESI_EMPLOYEE',
                'name' => 'ESI Employee',
                'category' => 'deduction',
                'component_type' => 'statutory',
                'calculation_method' => 'percentage_of_gross',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 220,
            ],
            [
                'code' => 'ESI_EMPLOYER',
                'name' => 'ESI Employer',
                'category' => 'employer_contribution',
                'component_type' => 'statutory',
                'calculation_method' => 'percentage_of_gross',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => false,
                'employer_only' => true,
                'arrear_eligible' => false,
                'display_order' => 230,
            ],
            [
                'code' => 'PROF_TAX',
                'name' => 'Professional Tax',
                'category' => 'deduction',
                'component_type' => 'tax',
                'calculation_method' => 'slab',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 240,
            ],
            [
                'code' => 'INCOME_TAX',
                'name' => 'Income Tax',
                'category' => 'deduction',
                'component_type' => 'tax',
                'calculation_method' => 'slab',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 250,
            ],
            [
                'code' => 'LOAN_RECOVERY',
                'name' => 'Loan Recovery',
                'category' => 'deduction',
                'component_type' => 'loan',
                'calculation_method' => 'manual_input',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 260,
            ],
            [
                'code' => 'INSURANCE',
                'name' => 'Insurance Deduction',
                'category' => 'deduction',
                'component_type' => 'insurance',
                'calculation_method' => 'manual_input',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 270,
            ],
            [
                'code' => 'CHARITY',
                'name' => 'Charitable Deduction',
                'category' => 'deduction',
                'component_type' => 'benefit',
                'calculation_method' => 'manual_input',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 280,
            ],
            [
                'code' => 'LWP_DEDUCTION',
                'name' => 'Leave Without Pay',
                'category' => 'deduction',
                'component_type' => 'adjustment',
                'calculation_method' => 'per_day',
                'taxable' => false,
                'pro_ratable' => false,
                'affects_gross' => false,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 290,
            ],
            [
                'code' => 'LEAVE_ENCASHMENT',
                'name' => 'Leave Encashment',
                'category' => 'earning',
                'component_type' => 'encashment',
                'calculation_method' => 'per_day',
                'taxable' => true,
                'pro_ratable' => false,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 100,
            ],
            [
                'code' => 'GRATUITY',
                'name' => 'Gratuity',
                'category' => 'earning',
                'component_type' => 'gratuity',
                'calculation_method' => 'formula',
                'taxable' => true,
                'pro_ratable' => false,
                'affects_gross' => true,
                'affects_net' => true,
                'employer_only' => false,
                'arrear_eligible' => false,
                'display_order' => 110,
            ],
        ];

        $timestamp = now();

        foreach ($components as $component) {
            DB::table('payroll_component_definitions')->updateOrInsert(
                ['code' => $component['code']],
                array_merge($component, [
                    'rounding_scale' => 2,
                    'status' => 'active',
                    'description' => null,
                    'formula_expression' => null,
                    'metadata' => null,
                    'created_at' => $timestamp,
                    'updated_at' => $timestamp,
                ])
            );
        }
    }
}
